set(EMCEE_SOURCE_FILES
        memory.cpp
        memory_dependent.cpp
        new.cpp
        new_allocation_block.cpp
        pow2.cpp
        reference_counter.cpp
        shared_count.cpp
        string.cpp
        util.cpp
        weak_count.cpp)